version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always


  quickstatements:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./etc/env
    ports:
      - "8765:80"
      - "8000:8000"
    volumes:
      - ./src:/home/wmb/www/src
    command: /home/wmb/www/cmd_run.sh
    restart: always

volumes:
  mariadb_data:
