version: '3.8'

x-application-service: &application-service
  build:
    context: ./
    dockerfile: Dockerfile
  depends_on:
    mariadb:
      condition: service_healthy
  restart: unless-stopped
  stdin_open: true
  tty: true
  environment: &application-environment
    DJANGO_SETTINGS_MODULE: qsts3.settings
    DB_NAME: quickstatements
    DB_USER: root # For dev/testing only.
    DB_PASSWORD: quickstatements_pass
    DB_HOST: mariadb
    STATIC_ROOT: /home/wmb/www/python/static
    QSTS_DEBUG: "True"
  env_file:
    - ./etc/env
  volumes:
    - ./src:/home/wmb/www/python/src
    - static-data:/home/wmb/www/python/static

services:
  mariadb:
    image: mariadb:11.7.2
    restart: unless-stopped
    environment:
      # For testing we need to create a new db automatically, so we *must*
      # use the root user
      MARIADB_DATABASE: quickstatements
      MARIADB_ROOT_PASSWORD: quickstatements_pass
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  webserver:
    image: nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - static-data:/static
      - ./etc/nginx.conf:/etc/nginx/nginx.conf

  app:
    <<: *application-service
    command: django-admin runserver 0.0.0.0:8000

  init_collect_static:
    <<: *application-service
    command: django-admin collectstatic --no-input
    restart: on-failure

  init_migrations:
    <<: *application-service
    command: django-admin migrate --no-input
    restart: on-failure

  run_send_batches:
    <<: *application-service
    depends_on:
      - init_migrations
    command: django-admin send_batches

volumes:
  mariadb_data:
  static-data:
