version: '3.8'

x-application-service: &application-service
  build:
    context: ./
    dockerfile: Dockerfile
  depends_on:
    mariadb:
      condition: service_healthy
  restart: unless-stopped
  environment: &application-environment
    DJANGO_SETTINGS_MODULE: qsts3.settings
    DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-quickstatements}
    DB_NAME: ${DB_NAME:-quickstatements}
    DB_USER: ${DB_USER:-root}
    DB_PASSWORD: ${DB_PASSWORD:-quickstatements}
    DB_HOST: ${DB_HOST:-mariadb}
    STATIC_ROOT: /home/wmb/www/python/static
    QSTS_DEBUG: "True"
  env_file:
    - ./etc/env
  volumes:
    - ./src:/home/wmb/www/python/src
    - static-data:/home/wmb/www/python/static

services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-quickstatements}"
      MYSQL_DATABASE: "${DB_NAME:-quickstatements}"
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  webserver:
    image: nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - static-data:/static
      - ./etc/nginx.conf:/etc/nginx/nginx.conf

  app:
    <<: *application-service
    command: django-admin runserver 0.0.0.0:8000

  init_collect_static:
    <<: *application-service
    command: django-admin collectstatic --no-input
    restart: on-failure

  init_migrations:
    <<: *application-service
    command: django-admin migrate --no-input
    restart: on-failure

  run_send_batches:
    <<: *application-service
    depends_on:
      - init_migrations
    command: django-admin send_batches

volumes:
  mariadb_data:
  static-data:
