version: '3.8'

x-application-service: &application-service
  build:
    context: ./
    dockerfile: Dockerfile
  depends_on:
    mariadb:
      condition: service_healthy
  restart: unless-stopped
  environment: &application-environment
    DJANGO_SETTINGS_MODULE: qsts3.settings
    DB_NAME: quickstatements
    DB_USER: root
    DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    DB_HOST: mariadb
    STATIC_ROOT: /home/wmb/www/static
    QSTS_DEBUG: "true"
  env_file:
    - ./etc/env
  volumes:
    - ./src:/home/wmb/www/src
    - static-data:/home/wmb/www/static

services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: quickstatements
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: quickstatements
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    <<: *application-service
    command: django-admin runserver 0.0.0.0:8000

  run_send_batches:
    <<: *application-service
    command: django-admin send_batches

  webserver:
    image: nginx
    restart: unless-stopped
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0640
    ports:
      - "8000:80"
    volumes:
      - static-data:/static

  init_collect_static:
    <<: *application-service
    command: django-admin collectstatic --no-input
    restart: on-failure

  init_migrations:
    <<: *application-service
    command: django-admin migrate --no-input
    restart: on-failure


configs:
  nginx_config:
    file: ./etc/nginx.conf

volumes:
  mariadb_data:
  static-data:
