# Generated by Django 5.0.6 on 2024-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchAdmin',
        ),
        migrations.DeleteModel(
            name='BatchCommandAdmin',
        ),
        migrations.AlterField(
            model_name='batch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
