# Generated by Django 5.0.7 on 2024-09-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_batch_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.IntegerField(
                choices=[(-1, "Blocked"), (0, "Initial"), (1, "Running"), (2, "Done")],
                db_index=True,
                default=0,
            ),
        ),
    ]
