# Generated by Django 5.0.9 on 2024-10-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_preferences_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
