# Generated by Django 5.0.8 on 2024-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_batch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchcommand",
            name="response_json",
            field=models.JSONField(default=dict),
        ),
    ]
