# Generated by Django 5.0.8 on 2024-09-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='block_on_errors',
            field=models.BooleanField(default=False),
        ),
    ]
