# Generated by Django 5.0.8 on 2024-10-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_batch_block_on_errors"),
        ("core", "0012_rename_data_type_verified_batchcommand_value_type_verified"),
    ]

    operations = []
