# Generated by Django 5.0.8 on 2024-10-07 22:30

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    Move 2->3 and 1->2 and 0->1
    """
    db_alias = schema_editor.connection.alias

    Batch = apps.get_model("core", "Batch")

    for b in Batch.objects.using(db_alias).filter(status=2):
        b.status = 3
        b.save()

    for b in Batch.objects.using(db_alias).filter(status=1):
        b.status = 2
        b.save()

    for b in Batch.objects.using(db_alias).filter(status=0):
        b.status = 1
        b.save()


def reverse_func(apps, schema_editor):
    """
    Move 1->0 and 2->1 and 3->2
    """
    db_alias = schema_editor.connection.alias

    Batch = apps.get_model("core", "Batch")

    for b in Batch.objects.using(db_alias).filter(status=2):
        b.status = 0
        b.save()

    for b in Batch.objects.using(db_alias).filter(status=2):
        b.status = 1
        b.save()

    for b in Batch.objects.using(db_alias).filter(status=3):
        b.status = 2
        b.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_merge_20241003_1539"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
