# Generated by Django 5.0.9 on 2024-11-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_batchcommand_user_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcommand',
            name='operation',
            field=models.TextField(choices=[('create_item', 'Create item')], null=True),
        ),
    ]
