# Generated by Django 5.0.9 on 2024-12-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_batchcommand_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchcommand",
            name="error",
            field=models.TextField(
                blank=True,
                choices=[
                    ("op_not_implemented", "Operation not implemented"),
                    ("no_statements_property", "No statements for given property"),
                    ("no_statements_value", "No statements with given value"),
                    ("sitelink_invalid", "The sitelink id is invalid"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="batchcommand",
            name="operation",
            field=models.TextField(
                blank=True,
                choices=[
                    ("create_item", "Create item"),
                    ("create_property", "Create property"),
                    ("remove_statement_by_id", "Remove statement by id"),
                    ("remove_statement_by_value", "Remove statement by value"),
                    ("set_sitelink", "Set sitelink"),
                ],
                null=True,
            ),
        ),
    ]
