# Generated by Django 5.0.9 on 2024-12-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_batchcommand_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchcommand",
            name="operation",
            field=models.TextField(
                blank=True,
                choices=[
                    ("create_item", "Create item"),
                    ("create_property", "Create property"),
                    ("remove_statement_by_id", "Remove statement by id"),
                    ("remove_statement_by_value", "Remove statement by value"),
                    ("set_sitelink", "Set sitelink"),
                    ("remove_sitelink", "Remove sitelink"),
                ],
                null=True,
            ),
        ),
    ]
