# Generated by Django 5.0.9 on 2026-06-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_batchcommand_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchcommand",
            name="error",
            field=models.TextField(
                blank=True,
                choices=[
                    ("op_not_implemented", "Operation not implemented"),
                    ("no_statements_property", "No statements for given property"),
                    ("no_statements_value", "No statements with given value"),
                    ("no_qualifiers", "No qualifiers with given value"),
                    ("no_reference_parts", "No reference parts with given value"),
                    ("sitelink_invalid", "The sitelink id is invalid"),
                    (
                        "data_policy_violation",
                        "An item with the same label and description already exists",
                    ),
                    ("combining_failed", "The next command failed"),
                    ("api_user_error", "API returned a User error"),
                    ("api_server_error", "API returned a server error"),
                    ("last_not_evaluated", "LAST could not be evaluated."),
                ],
                null=True,
            ),
        ),
    ]
