"""
Obtained from
https://doc.wikimedia.org/mediawiki-core/master/php/Names_8php_source.html
"""

LANGUAGE_CHOICES = (
    ("aa", "Qafár af"),
    ("aae", "Arbërisht"),
    ("ab", "аԥсшәа"),
    ("abs", "bahasa ambon"),
    ("ace", "Acèh"),
    ("acf", "Kwéyòl Sent Lisi"),
    ("acm", "عراقي"),
    ("ady", "адыгабзэ"),
    ("ady-cyrl", "адыгабзэ"),
    ("aeb", "تونسي / Tûnsî"),
    ("aeb-arab", "تونسي"),
    ("aeb-latn", "Tûnsî"),
    ("af", "Afrikaans"),
    ("aln", "Gegë"),
    ("als", "Alemannisch"),
    ("alt", "алтай тил"),
    ("am", "አማርኛ"),
    ("ami", "Pangcah"),
    ("an", "aragonés"),
    ("ang", "Ænglisc"),
    ("ann", "Obolo"),
    ("anp", "अंगिका"),
    ("apc", "شامي"),
    ("ar", "العربية"),
    ("arc", "ܐܪܡܝܐ"),
    ("arn", "mapudungun"),
    ("arq", "جازايرية"),
    ("ary", "الدارجة"),
    ("arz", "مصرى"),
    ("as", "অসমীয়া"),
    ("ase", "American sign language"),
    ("ast", "asturianu"),
    ("atj", "Atikamekw"),
    ("av", "авар"),
    ("avk", "Kotava"),
    ("awa", "अवधी"),
    ("ay", "Aymar aru"),
    ("az", "azərbaycanca"),
    ("azb", "تۆرکجه"),
    ("ba", "башҡортса"),
    ("ban", "Basa Bali"),
    ("ban-bali", "ᬩᬲᬩᬮᬶ"),
    ("bar", "Boarisch"),
    ("bat-smg", "žemaitėška"),
    ("bbc", "Batak Toba"),
    ("bbc-latn", "Batak Toba"),
    ("bcc", "جهلسری بلوچی"),
    ("bci", "wawle"),
    ("bcl", "Bikol Central"),
    ("bdr", "Bajau Sama"),
    ("be", "беларуская"),
    ("be-tarask", "беларуская (тарашкевіца)"),
    ("be-x-old", "беларуская (тарашкевіца)"),
    ("bew", "Betawi"),
    ("bg", "български"),
    ("bgc", "हरियाणवी"),
    ("bgn", "روچ کپتین بلوچی"),
    ("bh", "भोजपुरी"),
    ("bho", "भोजपुरी"),
    ("bi", "Bislama"),
    ("bjn", "Banjar"),
    ("blk", "ပအိုဝ်ႏဘာႏသာႏ"),
    ("bm", "bamanankan"),
    ("bn", "বাংলা"),
    ("bo", "བོད་ཡིག"),
    ("bpy", "বিষ্ণুপ্রিয়া মণিপুরী"),
    ("bqi", "بختیاری"),
    ("br", "brezhoneg"),
    ("brh", "Bráhuí"),
    ("bs", "bosanski"),
    ("btm", "Batak Mandailing"),
    ("bto", "Iriga Bicolano"),
    ("bug", "Basa Ugi"),
    ("bxr", "буряад"),
    ("ca", "català"),
    ("cbk-zam", "Chavacano de Zamboanga"),
    ("ccp", "𑄌𑄋𑄴𑄟𑄳𑄦"),
    ("cdo", "閩東語 / Mìng-dĕ̤ng-ngṳ̄"),
    ("ce", "нохчийн"),
    ("ceb", "Cebuano"),
    ("ch", "Chamoru"),
    ("chn", "chinuk wawa"),
    ("cho", "Chahta anumpa"),
    ("chr", "ᏣᎳᎩ"),
    ("chy", "Tsetsêhestâhese"),
    ("ckb", "کوردی"),
    ("co", "corsu"),
    ("cps", "Capiceño"),
    ("cpx", "莆仙語 / Pó-sing-gṳ̂"),
    ("cpx-hans", "莆仙语（简体）"),
    ("cpx-hant", "莆仙語（繁體）"),
    ("cpx-latn", "Pó-sing-gṳ̂ (Báⁿ-uā-ci̍)"),
    ("cr", "Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ"),
    ("crh", "qırımtatarca"),
    ("crh-cyrl", "къырымтатарджа (Кирилл)"),
    ("crh-latn", "qırımtatarca (Latin)"),
    ("crh-ro", "tatarşa"),
    ("cs", "čeština"),
    ("csb", "kaszëbsczi"),
    ("cu", "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ"),
    ("cv", "чӑвашла"),
    ("cy", "Cymraeg"),
    ("da", "dansk"),
    ("dag", "dagbanli"),
    ("de", "Deutsch"),
    ("de-at", "Österreichisches Deutsch"),
    ("de-ch", "Schweizer Hochdeutsch"),
    ("de-formal", "Deutsch (Sie-Form)"),
    ("dga", "Dagaare"),
    ("din", "Thuɔŋjäŋ"),
    ("diq", "Zazaki"),
    ("dsb", "dolnoserbski"),
    ("dtp", "Dusun Bundu-liwan"),
    ("dty", "डोटेली"),
    ("dv", "ދިވެހިބަސް"),
    ("dz", "ཇོང་ཁ"),
    ("ee", "eʋegbe"),
    ("efi", "Efịk"),
    ("egl", "Emiliàn"),
    ("el", "Ελληνικά"),
    ("eml", "emiliàn e rumagnòl"),
    ("en", "English"),
    ("en-ca", "Canadian English"),
    ("en-gb", "British English"),
    ("en-x-piglatin", "Igpay Atinlay"),
    ("eo", "Esperanto"),
    ("es", "español"),
    ("es-419", "español de América Latina"),
    ("es-formal", "español (formal)"),
    ("et", "eesti"),
    ("eu", "euskara"),
    ("ext", "estremeñu"),
    ("fa", "فارسی"),
    ("fat", "mfantse"),
    ("ff", "Fulfulde"),
    ("fi", "suomi"),
    ("fit", "meänkieli"),
    ("fiu-vro", "võro"),
    ("fj", "Na Vosa Vakaviti"),
    ("fo", "føroyskt"),
    ("fon", "fɔ̀ngbè"),
    ("fr", "français"),
    ("frc", "français cadien"),
    ("frp", "arpetan"),
    ("frr", "Nordfriisk"),
    ("fur", "furlan"),
    ("fy", "Frysk"),
    ("ga", "Gaeilge"),
    ("gaa", "Ga"),
    ("gag", "Gagauz"),
    ("gan", "贛語"),
    ("gan-hans", "赣语（简体）"),
    ("gan-hant", "贛語（繁體）"),
    ("gcf", "kréyòl Gwadloup"),
    ("gcr", "kriyòl gwiyannen"),
    ("gd", "Gàidhlig"),
    ("gl", "galego"),
    ("gld", "на̄ни"),
    ("glk", "گیلکی"),
    ("gn", "Avañe'ẽ"),
    ("gom", "गोंयची कोंकणी / Gõychi Konknni"),
    ("gom-deva", "गोंयची कोंकणी"),
    ("gom-latn", "Gõychi Konknni"),
    ("gor", "Bahasa Hulontalo"),
    ("got", "𐌲𐌿𐍄𐌹𐍃𐌺"),
    ("gpe", "Ghanaian Pidgin"),
    ("grc", "Ἀρχαία ἑλληνικὴ"),
    ("gsw", "Alemannisch"),
    ("gu", "ગુજરાતી"),
    ("guc", "wayuunaiki"),
    ("gur", "farefare"),
    ("guw", "gungbe"),
    ("gv", "Gaelg"),
    ("ha", "Hausa"),
    ("hak", "客家語 / Hak-kâ-ngî"),
    ("hak-hans", "客家语（简体）"),
    ("hak-hant", "客家語（繁體）"),
    ("hak-latn", "Hak-kâ-ngî (Pha̍k-fa-sṳ)"),
    ("haw", "Hawaiʻi"),
    ("he", "עברית"),
    ("hi", "हिन्दी"),
    ("hif", "Fiji Hindi"),
    ("hif-latn", "Fiji Hindi"),
    ("hil", "Ilonggo"),
    ("hno", "ہندکو"),
    ("ho", "Hiri Motu"),
    ("hr", "hrvatski"),
    ("hrx", "Hunsrik"),
    ("hsb", "hornjoserbsce"),
    ("hsn", "湘语"),
    ("ht", "Kreyòl ayisyen"),
    ("hu", "magyar"),
    ("hu-formal", "magyar (formal)"),
    ("hy", "հայերեն"),
    ("hyw", "Արեւմտահայերէն"),
    ("hz", "Otsiherero"),
    ("ia", "interlingua"),
    ("iba", "Jaku Iban"),
    ("ibb", "ibibio"),
    ("id", "Bahasa Indonesia"),
    ("ie", "Interlingue"),
    ("ig", "Igbo"),
    ("igl", "Igala"),
    ("ii", "ꆇꉙ"),
    ("ik", "Iñupiatun"),
    ("ike-cans", "ᐃᓄᒃᑎᑐᑦ"),
    ("ike-latn", "inuktitut"),
    ("ilo", "Ilokano"),
    ("inh", "гӀалгӀай"),
    ("io", "Ido"),
    ("is", "íslenska"),
    ("isv-latn", "medžuslovjansky"),
    ("it", "italiano"),
    ("iu", "ᐃᓄᒃᑎᑐᑦ / inuktitut"),
    ("ja", "日本語"),
    ("jam", "Patois"),
    ("jbo", "la .lojban."),
    ("jut", "jysk"),
    ("jv", "Jawa"),
    ("ka", "ქართული"),
    ("kaa", "Qaraqalpaqsha"),
    ("kab", "Taqbaylit"),
    ("kai", "Karai-karai"),
    ("kbd", "адыгэбзэ"),
    ("kbd-cyrl", "адыгэбзэ"),
    ("kbp", "Kabɩyɛ"),
    ("kcg", "Tyap"),
    ("kea", "kabuverdianu"),
    ("kg", "Kongo"),
    ("kge", "Basa Kumoring"),
    ("khw", "کھوار"),
    ("ki", "Gĩkũyũ"),
    ("kiu", "Kırmancki"),
    ("kj", "Kwanyama"),
    ("kjh", "хакас"),
    ("kjp", "ဖၠုံလိက်"),
    ("kk", "қазақша"),
    ("kk-arab", "قازاقشا (تٴوتە)"),
    ("kk-cn", "قازاقشا (جۇنگو)"),
    ("kk-cyrl", "қазақша (кирил)"),
    ("kk-kz", "қазақша (Қазақстан)"),
    ("kk-latn", "qazaqşa (latın)"),
    ("kk-tr", "qazaqşa (Türkïya)"),
    ("kl", "kalaallisut"),
    ("km", "ភាសាខ្មែរ"),
    ("kn", "ಕನ್ನಡ"),
    ("ko", "한국어"),
    ("ko-kp", "조선말"),
    ("koi", "перем коми"),
    ("kr", "kanuri"),
    ("krc", "къарачай-малкъар"),
    ("kri", "Krio"),
    ("krj", "Kinaray-a"),
    ("krl", "karjal"),
    ("ks", "कॉशुर / کٲشُر"),
    ("ks-arab", "کٲشُر"),
    ("ks-deva", "कॉशुर"),
    ("ksh", "Ripoarisch"),
    ("ksw", "စှီၤ"),
    ("ku", "kurdî"),
    ("ku-arab", "کوردی (عەرەبی)"),
    ("ku-latn", "kurdî (latînî)"),
    ("kum", "къумукъ"),
    ("kus", "Kʋsaal"),
    ("kv", "коми"),
    ("kw", "kernowek"),
    ("ky", "кыргызча"),
    ("la", "Latina"),
    ("lad", "Ladino"),
    ("lb", "Lëtzebuergesch"),
    ("lbe", "лакку"),
    ("lez", "лезги"),
    ("lfn", "Lingua Franca Nova"),
    ("lg", "Luganda"),
    ("li", "Limburgs"),
    ("lij", "Ligure"),
    ("liv", "Līvõ kēļ"),
    ("lki", "لەکی"),
    ("lld", "Ladin"),
    ("lmo", "lombard"),
    ("ln", "lingála"),
    ("lo", "ລາວ"),
    ("loz", "Silozi"),
    ("lrc", "لۊری شومالی"),
    ("lt", "lietuvių"),
    ("ltg", "latgaļu"),
    ("lus", "Mizo ţawng"),
    ("luz", "لئری دوٙمینی"),
    ("lv", "latviešu"),
    ("lzh", "文言"),
    ("lzz", "Lazuri"),
    ("mad", "Madhurâ"),
    ("mag", "मगही"),
    ("mai", "मैथिली"),
    ("map-bms", "Basa Banyumasan"),
    ("mdf", "мокшень"),
    ("mg", "Malagasy"),
    ("mh", "Ebon"),
    ("mhr", "олык марий"),
    ("mi", "Māori"),
    ("min", "Minangkabau"),
    ("mk", "македонски"),
    ("ml", "മലയാളം"),
    ("mn", "монгол"),
    ("mnc", "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ"),
    ("mnc-latn", "manju gisun"),
    ("mnc-mong", "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ"),
    ("mni", "ꯃꯤꯇꯩ ꯂꯣꯟ"),
    ("mnw", "ဘာသာမန်"),
    ("mo", "молдовеняскэ"),
    ("mos", "moore"),
    ("mr", "मराठी"),
    ("mrh", "Mara"),
    ("mrj", "кырык мары"),
    ("ms", "Bahasa Melayu"),
    ("ms-arab", "بهاس ملايو"),
    ("mt", "Malti"),
    ("mui", "Baso Palembang"),
    ("mus", "Mvskoke"),
    ("mwl", "Mirandés"),
    ("my", "မြန်မာဘာသာ"),
    ("myv", "эрзянь"),
    ("mzn", "مازِرونی"),
    ("na", "Dorerin Naoero"),
    ("nah", "Nāhuatl"),
    ("nan", "閩南語 / Bân-lâm-gú"),
    ("nan-hant", "閩南語（傳統漢字）"),
    ("nan-latn-pehoeji", "Bân-lâm-gú (Pe̍h-ōe-jī)"),
    ("nan-latn-tailo", "Bân-lâm-gú (Tâi-lô)"),
    ("nap", "Napulitano"),
    ("nb", "norsk bokmål"),
    ("nds", "Plattdüütsch"),
    ("nds-nl", "Nedersaksies"),
    ("ne", "नेपाली"),
    ("new", "नेपाल भाषा"),
    ("ng", "Oshiwambo"),
    ("nia", "Li Niha"),
    ("nit", "కొలామి"),
    ("niu", "Niuē"),
    ("nl", "Nederlands"),
    ("nl-informal", "Nederlands (informeel)"),
    ("nmz", "nawdm"),
    ("nn", "norsk nynorsk"),
    ("no", "norsk"),
    ("nod", "ᨣᩤᩴᨾᩮᩬᩥᨦ"),
    ("nog", "ногайша"),
    ("nov", "Novial"),
    ("nqo", "ߒߞߏ"),
    ("nrm", "Nouormand"),
    ("nso", "Sesotho sa Leboa"),
    ("nup", "Nupe"),
    ("nv", "Diné bizaad"),
    ("ny", "Chi-Chewa"),
    ("nyn", "runyankore"),
    ("nyo", "Orunyoro"),
    ("nys", "Nyunga"),
    ("oc", "occitan"),
    ("ojb", "Ojibwemowin"),
    ("olo", "livvinkarjala"),
    ("om", "Oromoo"),
    ("or", "ଓଡ଼ିଆ"),
    ("os", "ирон"),
    ("pa", "ਪੰਜਾਬੀ"),
    ("pag", "Pangasinan"),
    ("pam", "Kapampangan"),
    ("pap", "Papiamentu"),
    ("pcd", "Picard"),
    ("pcm", "Naijá"),
    ("pdc", "Deitsch"),
    ("pdt", "Plautdietsch"),
    ("pfl", "Pälzisch"),
    ("pi", "पालि"),
    ("pih", "Norfuk / Pitkern"),
    ("pl", "polski"),
    ("pms", "Piemontèis"),
    ("pnb", "پنجابی"),
    ("pnt", "Ποντιακά"),
    ("prg", "prūsiskan"),
    ("ps", "پښتو"),
    ("pt", "português"),
    ("pt-br", "português do Brasil"),
    ("pwn", "pinayuanan"),
    ("qu", "Runa Simi"),
    ("qug", "Runa shimi"),
    ("rgn", "Rumagnôl"),
    ("rif", "Tarifit"),
    ("rki", "ရခိုင်"),
    ("rm", "rumantsch"),
    ("rmc", "romaňi čhib"),
    ("rmy", "romani čhib"),
    ("rn", "ikirundi"),
    ("ro", "română"),
    ("roa-rup", "armãneashti"),
    ("roa-tara", "tarandíne"),
    ("rsk", "руски"),
    ("ru", "русский"),
    ("rue", "русиньскый"),
    ("rup", "armãneashti"),
    ("ruq", "Vlăheşte"),
    ("ruq-cyrl", "Влахесте"),
    ("ruq-latn", "Vlăheşte"),
    ("rut", "мыхаӀбишды"),
    ("rw", "Ikinyarwanda"),
    ("ryu", "うちなーぐち"),
    ("sa", "संस्कृतम्"),
    ("sah", "саха тыла"),
    ("sat", "ᱥᱟᱱᱛᱟᱲᱤ"),
    ("sc", "sardu"),
    ("scn", "sicilianu"),
    ("sco", "Scots"),
    ("sd", "سنڌي"),
    ("sdc", "Sassaresu"),
    ("sdh", "کوردی خوارگ"),
    ("se", "davvisámegiella"),
    ("se-fi", "davvisámegiella (Suoma bealde)"),
    ("se-no", "davvisámegiella (Norgga bealde)"),
    ("se-se", "davvisámegiella (Ruoŧa bealde)"),
    ("sei", "Cmique Itom"),
    ("ses", "Koyraboro Senni"),
    ("sg", "Sängö"),
    ("sgs", "žemaitėška"),
    ("sh", "srpskohrvatski / српскохрватски"),
    ("sh-cyrl", "српскохрватски (ћирилица)"),
    ("sh-latn", "srpskohrvatski (latinica)"),
    ("shi", "Taclḥit"),
    ("shi-latn", "Taclḥit"),
    ("shi-tfng", "ⵜⴰⵛⵍⵃⵉⵜ"),
    ("shn", "ၽႃႇသႃႇတႆး "),
    ("shy", "tacawit"),
    ("shy-latn", "tacawit"),
    ("si", "සිංහල"),
    ("simple", "Simple English"),
    ("sjd", "кӣллт са̄мь кӣлл"),
    ("sje", "bidumsámegiella"),
    ("sk", "slovenčina"),
    ("skr", "سرائیکی"),
    ("skr-arab", "سرائیکی"),
    ("sl", "slovenščina"),
    ("sli", "Schläsch"),
    ("sm", "Gagana Samoa"),
    ("sma", "åarjelsaemien"),
    ("smn", "anarâškielâ"),
    ("sms", "nuõrttsääʹmǩiõll"),
    ("sn", "chiShona"),
    ("so", "Soomaaliga"),
    ("sq", "shqip"),
    ("sr", "српски / srpski"),
    ("sr-ec", "српски (ћирилица)"),
    ("sr-el", "srpski (latinica)"),
    ("srn", "Sranantongo"),
    ("sro", "sardu campidanesu"),
    ("ss", "SiSwati"),
    ("st", "Sesotho"),
    ("stq", "Seeltersk"),
    ("sty", "себертатар"),
    ("su", "Sunda"),
    ("sv", "svenska"),
    ("sw", "Kiswahili"),
    ("syl", "ꠍꠤꠟꠐꠤ"),
    ("szl", "ślůnski"),
    ("szy", "Sakizaya"),
    ("ta", "தமிழ்"),
    ("tay", "Tayal"),
    ("tcy", "ತುಳು"),
    ("tdd", "ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ"),
    ("te", "తెలుగు"),
    ("tet", "tetun"),
    ("tg", "тоҷикӣ"),
    ("tg-cyrl", "тоҷикӣ"),
    ("tg-latn", "tojikī"),
    ("th", "ไทย"),
    ("ti", "ትግርኛ"),
    ("tk", "Türkmençe"),
    ("tl", "Tagalog"),
    ("tly", "tolışi"),
    ("tly-cyrl", "толыши"),
    ("tn", "Setswana"),
    ("to", "lea faka-Tonga"),
    ("tok", "toki pona"),
    ("tpi", "Tok Pisin"),
    ("tr", "Türkçe"),
    ("tru", "Ṫuroyo"),
    ("trv", "Seediq"),
    ("ts", "Xitsonga"),
    ("tt", "татарча / tatarça"),
    ("tt-cyrl", "татарча"),
    ("tt-latn", "tatarça"),
    ("ttj", "Orutooro"),
    ("tum", "chiTumbuka"),
    ("tw", "Twi"),
    ("ty", "reo tahiti"),
    ("tyv", "тыва дыл"),
    ("tzm", "ⵜⴰⵎⴰⵣⵉⵖⵜ"),
    ("udm", "удмурт"),
    ("ug", "ئۇيغۇرچە / Uyghurche"),
    ("ug-arab", "ئۇيغۇرچە"),
    ("ug-latn", "Uyghurche"),
    ("uk", "українська"),
    ("ur", "اردو"),
    ("uz", "oʻzbekcha / ўзбекча"),
    ("uz-cyrl", "ўзбекча"),
    ("uz-latn", "oʻzbekcha"),
    ("ve", "Tshivenda"),
    ("vec", "vèneto"),
    ("vep", "vepsän kel’"),
    ("vi", "Tiếng Việt"),
    ("vls", "West-Vlams"),
    ("vmf", "Mainfränkisch"),
    ("vmw", "emakhuwa"),
    ("vo", "Volapük"),
    ("vot", "Vaďďa"),
    ("vro", "võro"),
    ("wa", "walon"),
    ("wal", "wolaytta"),
    ("war", "Winaray"),
    ("wls", "Fakaʻuvea"),
    ("wo", "Wolof"),
    ("wuu", "吴语"),
    ("wuu-hans", "吴语（简体）"),
    ("wuu-hant", "吳語（正體）"),
    ("xal", "хальмг"),
    ("xh", "isiXhosa"),
    ("xmf", "მარგალური"),
    ("xsy", "saisiyat"),
    ("yi", "ייִדיש"),
    ("yo", "Yorùbá"),
    ("yrl", "Nhẽẽgatú"),
    ("yue", "粵語"),
    ("yue-hans", "粵语（简体）"),
    ("yue-hant", "粵語（繁體）"),
    ("za", "Vahcuengh"),
    ("zea", "Zeêuws"),
    ("zgh", "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ"),
    ("zgh-latn", "tamaziɣt tanawayt"),
    ("zh", "中文"),
    ("zh-classical", "文言"),
    ("zh-cn", "中文（中国大陆）"),
    ("zh-hans", "中文（简体）"),
    ("zh-hant", "中文（繁體）"),
    ("zh-hk", "中文（香港）"),
    ("zh-min-nan", "Bân-lâm-gú"),
    ("zh-mo", "中文（澳門）"),
    ("zh-my", "中文（马来西亚）"),
    ("zh-sg", "中文（新加坡）"),
    ("zh-tw", "中文（臺灣）"),
    ("zh-yue", "粵語"),
    ("zu", "isiZulu"),
)
